// OfficeMacroGpoData.cpp

#include "OfficeMacroGpoData.h"

// All the below is autogenerated using MitigationsAllToCpp.ps1, using input data built by Policy Analyzer.

// ------------------------------------------------------------------------------------------
// Define string constants

const wchar_t* const szGpPath_MicrosoftAccess2016ApplicationSettingsSecurityTrustCenter = L"Microsoft Access 2016\\Application Settings\\Security\\Trust Center";
const wchar_t* const szGpPath_MicrosoftAccess2016ApplicationSettingsSecurityTrustCenterTrustedLocations = L"Microsoft Access 2016\\Application Settings\\Security\\Trust Center\\Trusted Locations";
const wchar_t* const szGpPath_MicrosoftExcel2016ExcelOptionsSecurity = L"Microsoft Excel 2016\\Excel Options\\Security";
const wchar_t* const szGpPath_MicrosoftExcel2016ExcelOptionsSecurityTrustCenter = L"Microsoft Excel 2016\\Excel Options\\Security\\Trust Center";
const wchar_t* const szGpPath_MicrosoftExcel2016ExcelOptionsSecurityTrustCenterFileBlockSettings = L"Microsoft Excel 2016\\Excel Options\\Security\\Trust Center\\File Block Settings";
const wchar_t* const szGpPath_MicrosoftExcel2016ExcelOptionsSecurityTrustCenterTrustedLocations = L"Microsoft Excel 2016\\Excel Options\\Security\\Trust Center\\Trusted Locations";
const wchar_t* const szGpPath_MicrosoftOffice2016MachineSecuritySettings = L"Microsoft Office 2016 (Machine)\\Security Settings";
const wchar_t* const szGpPath_MicrosoftPowerPoint2016PowerPointOptionsSecurity = L"Microsoft PowerPoint 2016\\PowerPoint Options\\Security";
const wchar_t* const szGpPath_MicrosoftPowerPoint2016PowerPointOptionsSecurityTrustCenter = L"Microsoft PowerPoint 2016\\PowerPoint Options\\Security\\Trust Center";
const wchar_t* const szGpPath_MicrosoftPowerPoint2016PowerPointOptionsSecurityTrustCenterFileBlockSettings = L"Microsoft PowerPoint 2016\\PowerPoint Options\\Security\\Trust Center\\File Block Settings";
const wchar_t* const szGpPath_MicrosoftPowerPoint2016PowerPointOptionsSecurityTrustCenterTrustedLocations = L"Microsoft PowerPoint 2016\\PowerPoint Options\\Security\\Trust Center\\Trusted Locations";
const wchar_t* const szGpPath_MicrosoftProject2016ProjectOptionsSecurity = L"Microsoft Project 2016\\Project Options\\Security";
const wchar_t* const szGpPath_MicrosoftProject2016ProjectOptionsSecurityTrustCenter = L"Microsoft Project 2016\\Project Options\\Security\\Trust Center";
const wchar_t* const szGpPath_MicrosoftPublisher2016SecurityTrustCenter = L"Microsoft Publisher 2016\\Security\\Trust Center";
const wchar_t* const szGpPath_MicrosoftVisio2016VisioOptionsSecurityTrustCenter = L"Microsoft Visio 2016\\Visio Options\\Security\\Trust Center";
const wchar_t* const szGpPath_MicrosoftVisio2016VisioOptionsSecurityTrustCenterFileBlockSettings = L"Microsoft Visio 2016\\Visio Options\\Security\\Trust Center\\File Block Settings";
const wchar_t* const szGpPath_MicrosoftWord2016WordOptionsSecurityTrustCenter = L"Microsoft Word 2016\\Word Options\\Security\\Trust Center";
const wchar_t* const szGpPath_MicrosoftWord2016WordOptionsSecurityTrustCenterFileBlockSettings = L"Microsoft Word 2016\\Word Options\\Security\\Trust Center\\File Block Settings";
const wchar_t* const szGpPath_MicrosoftWord2016WordOptionsSecurityTrustCenterTrustedLocations = L"Microsoft Word 2016\\Word Options\\Security\\Trust Center\\Trusted Locations";
const wchar_t* const szGpPath_WindowsComponentsMicrosoftDefenderAntivirusMicrosoftDefenderExploitGuardAttackSurfaceReduction = L"Windows Components\\Microsoft Defender Antivirus\\Microsoft Defender Exploit Guard\\Attack Surface Reduction";
const wchar_t* const szGpPath_WindowsComponentsMicrosoftDefenderAntivirusReal_timeProtection = L"Windows Components\\Microsoft Defender Antivirus\\Real-time Protection";

const wchar_t* const szGpName_ASRRuleBlockallOfficeapplicationsfromcreatingchildprocesses = L"ASR Rule: Block all Office applications from creating child processes";
const wchar_t* const szGpName_ASRRuleBlockOfficeapplicationsfromcreatingexecutablecontent = L"ASR Rule: Block Office applications from creating executable content";
const wchar_t* const szGpName_ASRRuleBlockOfficeapplicationsfrominjectingcodeintootherprocesses = L"ASR Rule: Block Office applications from injecting code into other processes";
const wchar_t* const szGpName_ASRRuleBlockOfficecommunicationapplicationfromcreatingchildprocesses = L"ASR Rule: Block Office communication application from creating child processes";
const wchar_t* const szGpName_ASRRuleBlockWin32APIcallsfromOfficemacro = L"ASR Rule: Block Win32 API calls from Office macro";
const wchar_t* const szGpName_BlockmacrosfromrunninginOfficefilesfromtheInternet = L"Block macros from running in Office files from the Internet";
const wchar_t* const szGpName_ConfigureAttackSurfaceReductionrules = L"Configure Attack Surface Reduction rules";
const wchar_t* const szGpName_dBaseIIIIVfiles = L"dBase III / IV files";
const wchar_t* const szGpName_DifandSylkfiles = L"Dif and Sylk files";
const wchar_t* const szGpName_Disablealltrustedlocations = L"Disable all trusted locations";
const wchar_t* const szGpName_DisableTrustBarNotificationforunsignedapplicationadd_insandblockthem = L"Disable Trust Bar Notification for unsigned application add-ins and block them";
const wchar_t* const szGpName_DisableVBAforOfficeapplications = L"Disable VBA for Office applications";
const wchar_t* const szGpName_Excel2macrosheetsandadd_infiles = L"Excel 2 macrosheets and add-in files";
const wchar_t* const szGpName_Excel2worksheets = L"Excel 2 worksheets";
const wchar_t* const szGpName_Excel3macrosheetsandadd_infiles = L"Excel 3 macrosheets and add-in files";
const wchar_t* const szGpName_Excel3worksheets = L"Excel 3 worksheets";
const wchar_t* const szGpName_Excel4macrosheetsandadd_infiles = L"Excel 4 macrosheets and add-in files";
const wchar_t* const szGpName_Excel4workbooks = L"Excel 4 workbooks";
const wchar_t* const szGpName_Excel4worksheets = L"Excel 4 worksheets";
const wchar_t* const szGpName_Excel95workbooks = L"Excel 95 workbooks";
const wchar_t* const szGpName_Excel95_97workbooksandtemplates = L"Excel 95-97 workbooks and templates";
const wchar_t* const szGpName_Excel97_2003workbooksandtemplates = L"Excel 97-2003 workbooks and templates";
const wchar_t* const szGpName_MacroNotificationSettings = L"Macro Notification Settings";
const wchar_t* const szGpName_MacroNotificationSettings__Blockcertificatesfromtrustedpublishersthatareonlyinstalledinthecurrentusercertificatestore = L"Macro Notification Settings --> Block certificates from trusted publishers that are only installed in the current user certificate store";
const wchar_t* const szGpName_MacroNotificationSettings__RequireExtendedKeyUsageEKUforcertificatesfromtrustedpublishers = L"Macro Notification Settings --> Require Extended Key Usage (EKU) for certificates from trusted publishers";
const wchar_t* const szGpName_MacroNotificationSettings__Requiremacrostobesignedbyatrustedpublisher = L"Macro Notification Settings --> Require macros to be signed by a trusted publisher";
const wchar_t* const szGpName_PowerPoint97_2003presentationsshowstemplatesandadd_infiles = L"PowerPoint 97-2003 presentations, shows, templates and add-in files";
const wchar_t* const szGpName_Previous_versionfileformats = L"Previous-version file formats";
const wchar_t* const szGpName_Requirethatapplicationadd_insaresignedbyTrustedPublisher = L"Require that application add-ins are signed by Trusted Publisher";
const wchar_t* const szGpName_ScanencryptedmacrosinExcelOpenXMLworkbooks = L"Scan encrypted macros in Excel Open XML workbooks";
const wchar_t* const szGpName_ScanencryptedmacrosinPowerPointOpenXMLpresentations = L"Scan encrypted macros in PowerPoint Open XML presentations";
const wchar_t* const szGpName_ScanencryptedmacrosinWordOpenXMLdocuments = L"Scan encrypted macros in Word Open XML documents";
const wchar_t* const szGpName_Setdefaultfileblockbehavior = L"Set default file block behavior";
const wchar_t* const szGpName_Turnoffreal_timeprotection = L"Turn off real-time protection";
const wchar_t* const szGpName_VBAMacroNotificationSettings = L"VBA Macro Notification Settings";
const wchar_t* const szGpName_VBAMacroNotificationSettings__Blockcertificatesfromtrustedpublishersthatareonlyinstalledinthecurrentusercertificatestore = L"VBA Macro Notification Settings --> Block certificates from trusted publishers that are only installed in the current user certificate store";
const wchar_t* const szGpName_VBAMacroNotificationSettings__RequireExtendedKeyUsageEKUforcertificatesfromtrustedpublishers = L"VBA Macro Notification Settings --> Require Extended Key Usage (EKU) for certificates from trusted publishers";
const wchar_t* const szGpName_VBAMacroNotificationSettings__Requiremacrostobesignedbyatrustedpublisher = L"VBA Macro Notification Settings --> Require macros to be signed by a trusted publisher";
const wchar_t* const szGpName_Visio2000_2002BinaryDrawingsTemplatesandStencils = L"Visio 2000-2002 Binary Drawings, Templates and Stencils";
const wchar_t* const szGpName_Visio2003_2010BinaryDrawingsTemplatesandStencils = L"Visio 2003-2010 Binary Drawings, Templates and Stencils";
const wchar_t* const szGpName_Visio50orearlierBinaryDrawingsTemplatesandStencils = L"Visio 5.0 or earlier Binary Drawings, Templates and Stencils";
const wchar_t* const szGpName_WebpagesandExcel2003XMLspreadsheets = L"Web pages and Excel 2003 XML spreadsheets";
const wchar_t* const szGpName_Word2andearlierbinarydocumentsandtemplates = L"Word 2 and earlier binary documents and templates";
const wchar_t* const szGpName_Word2000binarydocumentsandtemplates = L"Word 2000 binary documents and templates";
const wchar_t* const szGpName_Word2003binarydocumentsandtemplates = L"Word 2003 binary documents and templates";
const wchar_t* const szGpName_Word2007andlaterbinarydocumentsandtemplates = L"Word 2007 and later binary documents and templates";
const wchar_t* const szGpName_Word60binarydocumentsandtemplates = L"Word 6.0 binary documents and templates";
const wchar_t* const szGpName_Word95binarydocumentsandtemplates = L"Word 95 binary documents and templates";
const wchar_t* const szGpName_Word97binarydocumentsandtemplates = L"Word 97 binary documents and templates";
const wchar_t* const szGpName_WordXPbinarydocumentsandtemplates = L"Word XP binary documents and templates";

const wchar_t* const szRegKey_softwarepoliciesmicrosoftoffice160accesssecurity = L"software\\policies\\microsoft\\office\\16.0\\access\\security";
const wchar_t* const szRegKey_softwarepoliciesmicrosoftoffice160accesssecuritytrustedlocations = L"software\\policies\\microsoft\\office\\16.0\\access\\security\\trusted locations";
const wchar_t* const szRegKey_softwarepoliciesmicrosoftoffice160common = L"software\\policies\\microsoft\\office\\16.0\\common";
const wchar_t* const szRegKey_softwarepoliciesmicrosoftoffice160excelsecurity = L"software\\policies\\microsoft\\office\\16.0\\excel\\security";
const wchar_t* const szRegKey_softwarepoliciesmicrosoftoffice160excelsecurityfileblock = L"software\\policies\\microsoft\\office\\16.0\\excel\\security\\fileblock";
const wchar_t* const szRegKey_softwarepoliciesmicrosoftoffice160excelsecuritytrustedlocations = L"software\\policies\\microsoft\\office\\16.0\\excel\\security\\trusted locations";
const wchar_t* const szRegKey_softwarepoliciesmicrosoftoffice160msprojectsecurity = L"software\\policies\\microsoft\\office\\16.0\\ms project\\security";
const wchar_t* const szRegKey_softwarepoliciesmicrosoftoffice160msprojectsecuritytrustedlocations = L"software\\policies\\microsoft\\office\\16.0\\ms project\\security\\trusted locations";
const wchar_t* const szRegKey_softwarepoliciesmicrosoftoffice160powerpointsecurity = L"software\\policies\\microsoft\\office\\16.0\\powerpoint\\security";
const wchar_t* const szRegKey_softwarepoliciesmicrosoftoffice160powerpointsecurityfileblock = L"software\\policies\\microsoft\\office\\16.0\\powerpoint\\security\\fileblock";
const wchar_t* const szRegKey_softwarepoliciesmicrosoftoffice160powerpointsecuritytrustedlocations = L"software\\policies\\microsoft\\office\\16.0\\powerpoint\\security\\trusted locations";
const wchar_t* const szRegKey_softwarepoliciesmicrosoftoffice160publishersecurity = L"software\\policies\\microsoft\\office\\16.0\\publisher\\security";
const wchar_t* const szRegKey_softwarepoliciesmicrosoftoffice160visiosecurity = L"software\\policies\\microsoft\\office\\16.0\\visio\\security";
const wchar_t* const szRegKey_softwarepoliciesmicrosoftoffice160visiosecurityfileblock = L"software\\policies\\microsoft\\office\\16.0\\visio\\security\\fileblock";
const wchar_t* const szRegKey_softwarepoliciesmicrosoftoffice160visiosecuritytrustedlocations = L"software\\policies\\microsoft\\office\\16.0\\visio\\security\\trusted locations";
const wchar_t* const szRegKey_softwarepoliciesmicrosoftoffice160wordsecurity = L"software\\policies\\microsoft\\office\\16.0\\word\\security";
const wchar_t* const szRegKey_softwarepoliciesmicrosoftoffice160wordsecurityfileblock = L"software\\policies\\microsoft\\office\\16.0\\word\\security\\fileblock";
const wchar_t* const szRegKey_softwarepoliciesmicrosoftoffice160wordsecuritytrustedlocations = L"software\\policies\\microsoft\\office\\16.0\\word\\security\\trusted locations";
const wchar_t* const szRegKey_SoftwarePoliciesMicrosoftWindowsDefenderReal_TimeProtection = L"Software\\Policies\\Microsoft\\Windows Defender\\Real-Time Protection";
const wchar_t* const szRegKey_SoftwarePoliciesMicrosoftWindowsDefenderWindowsDefenderExploitGuardASR = L"Software\\Policies\\Microsoft\\Windows Defender\\Windows Defender Exploit Guard\\ASR";
const wchar_t* const szRegKey_SoftwarePoliciesMicrosoftWindowsDefenderWindowsDefenderExploitGuardASRRules = L"Software\\Policies\\Microsoft\\Windows Defender\\Windows Defender Exploit Guard\\ASR\\Rules";

const wchar_t* const szRegVal_26190899_1602_49e8_8b27_eb1d0a1ce869 = L"26190899-1602-49e8-8b27-eb1d0a1ce869";
const wchar_t* const szRegVal_3b576869_a4ec_4529_8536_b80a7769e899 = L"3b576869-a4ec-4529-8536-b80a7769e899";
const wchar_t* const szRegVal_75668c1f_73b5_4cf0_bb93_3ecf5cb7cc84 = L"75668c1f-73b5-4cf0-bb93-3ecf5cb7cc84";
const wchar_t* const szRegVal_92E97FA1_2EDF_4476_BDD6_9DD0B4DDDC7B = L"92E97FA1-2EDF-4476-BDD6-9DD0B4DDDC7B";
const wchar_t* const szRegVal_alllocationsdisabled = L"alllocationsdisabled";
const wchar_t* const szRegVal_binaryfiles = L"binaryfiles";
const wchar_t* const szRegVal_blockcontentexecutionfrominternet = L"blockcontentexecutionfrominternet";
const wchar_t* const szRegVal_d4f940ab_401b_4efc_aadc_ad5f3c50688a = L"d4f940ab-401b-4efc-aadc-ad5f3c50688a";
const wchar_t* const szRegVal_dbasefiles = L"dbasefiles";
const wchar_t* const szRegVal_difandsylkfiles = L"difandsylkfiles";
const wchar_t* const szRegVal_DisableRealtimeMonitoring = L"DisableRealtimeMonitoring";
const wchar_t* const szRegVal_excelbypassencryptedmacroscan = L"excelbypassencryptedmacroscan";
const wchar_t* const szRegVal_ExploitGuard_ASR_Rules = L"ExploitGuard_ASR_Rules";
const wchar_t* const szRegVal_htmlandxmlssfiles = L"htmlandxmlssfiles";
const wchar_t* const szRegVal_legacyfiles = L"legacyfiles";
const wchar_t* const szRegVal_notbpromptunsignedaddin = L"notbpromptunsignedaddin";
const wchar_t* const szRegVal_openinprotectedview = L"openinprotectedview";
const wchar_t* const szRegVal_powerpointbypassencryptedmacroscan = L"powerpointbypassencryptedmacroscan";
const wchar_t* const szRegVal_requireaddinsig = L"requireaddinsig";
const wchar_t* const szRegVal_vbadigsigtrustedpublishers = L"vbadigsigtrustedpublishers";
const wchar_t* const szRegVal_vbaoff = L"vbaoff";
const wchar_t* const szRegVal_vbarequiredigsigwithcodesigningeku = L"vbarequiredigsigwithcodesigningeku";
const wchar_t* const szRegVal_vbarequirelmtrustedpublisher = L"vbarequirelmtrustedpublisher";
const wchar_t* const szRegVal_vbawarnings = L"vbawarnings";
const wchar_t* const szRegVal_visio2000files = L"visio2000files";
const wchar_t* const szRegVal_visio2003files = L"visio2003files";
const wchar_t* const szRegVal_visio50andearlierfiles = L"visio50andearlierfiles";
const wchar_t* const szRegVal_word2000files = L"word2000files";
const wchar_t* const szRegVal_word2003files = L"word2003files";
const wchar_t* const szRegVal_word2007files = L"word2007files";
const wchar_t* const szRegVal_word2files = L"word2files";
const wchar_t* const szRegVal_word60files = L"word60files";
const wchar_t* const szRegVal_word95files = L"word95files";
const wchar_t* const szRegVal_word97files = L"word97files";
const wchar_t* const szRegVal_wordbypassencryptedmacroscan = L"wordbypassencryptedmacroscan";
const wchar_t* const szRegVal_wordxpfiles = L"wordxpfiles";
const wchar_t* const szRegVal_xl2macros = L"xl2macros";
const wchar_t* const szRegVal_xl2worksheets = L"xl2worksheets";
const wchar_t* const szRegVal_xl3macros = L"xl3macros";
const wchar_t* const szRegVal_xl3worksheets = L"xl3worksheets";
const wchar_t* const szRegVal_xl4macros = L"xl4macros";
const wchar_t* const szRegVal_xl4workbooks = L"xl4workbooks";
const wchar_t* const szRegVal_xl4worksheets = L"xl4worksheets";
const wchar_t* const szRegVal_xl9597workbooksandtemplates = L"xl9597workbooksandtemplates";
const wchar_t* const szRegVal_xl95workbooks = L"xl95workbooks";
const wchar_t* const szRegVal_xl97workbooksandtemplates = L"xl97workbooksandtemplates";

// ------------------------------------------------------------------------------------------
// DisableAllVBA - setting definitions

const GpoDefn_t DisableAllVBA_1_vbaoff = {
    true,
    szGpPath_MicrosoftOffice2016MachineSecuritySettings,
    szGpName_DisableVBAforOfficeapplications,
    szRegKey_softwarepoliciesmicrosoftoffice160common,
    szRegVal_vbaoff };

// DisableAllVBA - choice definitions

const GpoItemChoice_t DisableAllVBA_choice_Enabled = { L"Enabled", REG_DWORD, 1 };

// ------------------------------------------------------------------------------------------
// ASR - setting definitions

const GpoDefn_t ASR_1_ExploitGuard_ASR_Rules = {
    true,
    szGpPath_WindowsComponentsMicrosoftDefenderAntivirusMicrosoftDefenderExploitGuardAttackSurfaceReduction,
    szGpName_ConfigureAttackSurfaceReductionrules,
    szRegKey_SoftwarePoliciesMicrosoftWindowsDefenderWindowsDefenderExploitGuardASR,
    szRegVal_ExploitGuard_ASR_Rules };
const GpoDefn_t ASR_2_26190899_1602_49e8_8b27_eb1d0a1ce869 = {
    true,
    szGpPath_WindowsComponentsMicrosoftDefenderAntivirusMicrosoftDefenderExploitGuardAttackSurfaceReduction,
    szGpName_ASRRuleBlockOfficecommunicationapplicationfromcreatingchildprocesses,
    szRegKey_SoftwarePoliciesMicrosoftWindowsDefenderWindowsDefenderExploitGuardASRRules,
    szRegVal_26190899_1602_49e8_8b27_eb1d0a1ce869 };
const GpoDefn_t ASR_3_3b576869_a4ec_4529_8536_b80a7769e899 = {
    true,
    szGpPath_WindowsComponentsMicrosoftDefenderAntivirusMicrosoftDefenderExploitGuardAttackSurfaceReduction,
    szGpName_ASRRuleBlockOfficeapplicationsfromcreatingexecutablecontent,
    szRegKey_SoftwarePoliciesMicrosoftWindowsDefenderWindowsDefenderExploitGuardASRRules,
    szRegVal_3b576869_a4ec_4529_8536_b80a7769e899 };
const GpoDefn_t ASR_4_75668c1f_73b5_4cf0_bb93_3ecf5cb7cc84 = {
    true,
    szGpPath_WindowsComponentsMicrosoftDefenderAntivirusMicrosoftDefenderExploitGuardAttackSurfaceReduction,
    szGpName_ASRRuleBlockOfficeapplicationsfrominjectingcodeintootherprocesses,
    szRegKey_SoftwarePoliciesMicrosoftWindowsDefenderWindowsDefenderExploitGuardASRRules,
    szRegVal_75668c1f_73b5_4cf0_bb93_3ecf5cb7cc84 };
const GpoDefn_t ASR_5_92E97FA1_2EDF_4476_BDD6_9DD0B4DDDC7B = {
    true,
    szGpPath_WindowsComponentsMicrosoftDefenderAntivirusMicrosoftDefenderExploitGuardAttackSurfaceReduction,
    szGpName_ASRRuleBlockWin32APIcallsfromOfficemacro,
    szRegKey_SoftwarePoliciesMicrosoftWindowsDefenderWindowsDefenderExploitGuardASRRules,
    szRegVal_92E97FA1_2EDF_4476_BDD6_9DD0B4DDDC7B };
const GpoDefn_t ASR_6_d4f940ab_401b_4efc_aadc_ad5f3c50688a = {
    true,
    szGpPath_WindowsComponentsMicrosoftDefenderAntivirusMicrosoftDefenderExploitGuardAttackSurfaceReduction,
    szGpName_ASRRuleBlockallOfficeapplicationsfromcreatingchildprocesses,
    szRegKey_SoftwarePoliciesMicrosoftWindowsDefenderWindowsDefenderExploitGuardASRRules,
    szRegVal_d4f940ab_401b_4efc_aadc_ad5f3c50688a };
const GpoDefn_t ASR_7_DisableRealtimeMonitoring = {
    true,
    szGpPath_WindowsComponentsMicrosoftDefenderAntivirusReal_timeProtection,
    szGpName_Turnoffreal_timeprotection,
    szRegKey_SoftwarePoliciesMicrosoftWindowsDefenderReal_TimeProtection,
    szRegVal_DisableRealtimeMonitoring };

// ASR - choice definitions

const GpoItemChoice_t ASR_choice_Enabled = { L"Enabled", REG_DWORD, 1 };
const GpoItemChoice_t ASR_choice_Audit = { L"Audit", REG_SZ, 2 };
const GpoItemChoice_t ASR_choice_Block = { L"Block", REG_SZ, 1 };
const GpoItemChoice_t ASR_choice_Off = { L"Off", REG_SZ, 0 };
const GpoItemChoice_t ASR_choice_Warn = { L"Warn", REG_SZ, 6 };
const GpoItemChoice_t ASR_choice_Disabled = { L"Disabled", REG_DWORD, 0 };

// ------------------------------------------------------------------------------------------
// BlockMacrosFromRunningInOfficeFilesFromTheInternet - setting definitions

const GpoDefn_t BlockMacrosFromRunningInOfficeFilesFromTheInternet_1_blockcontentexecutionfrominternet = {
    false,
    szGpPath_MicrosoftAccess2016ApplicationSettingsSecurityTrustCenter,
    szGpName_BlockmacrosfromrunninginOfficefilesfromtheInternet,
    szRegKey_softwarepoliciesmicrosoftoffice160accesssecurity,
    szRegVal_blockcontentexecutionfrominternet };
const GpoDefn_t BlockMacrosFromRunningInOfficeFilesFromTheInternet_2_blockcontentexecutionfrominternet = {
    false,
    szGpPath_MicrosoftExcel2016ExcelOptionsSecurityTrustCenter,
    szGpName_BlockmacrosfromrunninginOfficefilesfromtheInternet,
    szRegKey_softwarepoliciesmicrosoftoffice160excelsecurity,
    szRegVal_blockcontentexecutionfrominternet };
const GpoDefn_t BlockMacrosFromRunningInOfficeFilesFromTheInternet_3_blockcontentexecutionfrominternet = {
    false,
    szGpPath_MicrosoftPowerPoint2016PowerPointOptionsSecurityTrustCenter,
    szGpName_BlockmacrosfromrunninginOfficefilesfromtheInternet,
    szRegKey_softwarepoliciesmicrosoftoffice160powerpointsecurity,
    szRegVal_blockcontentexecutionfrominternet };
const GpoDefn_t BlockMacrosFromRunningInOfficeFilesFromTheInternet_4_blockcontentexecutionfrominternet = {
    false,
    szGpPath_MicrosoftVisio2016VisioOptionsSecurityTrustCenter,
    szGpName_BlockmacrosfromrunninginOfficefilesfromtheInternet,
    szRegKey_softwarepoliciesmicrosoftoffice160visiosecurity,
    szRegVal_blockcontentexecutionfrominternet };
const GpoDefn_t BlockMacrosFromRunningInOfficeFilesFromTheInternet_5_blockcontentexecutionfrominternet = {
    false,
    szGpPath_MicrosoftWord2016WordOptionsSecurityTrustCenter,
    szGpName_BlockmacrosfromrunninginOfficefilesfromtheInternet,
    szRegKey_softwarepoliciesmicrosoftoffice160wordsecurity,
    szRegVal_blockcontentexecutionfrominternet };

// BlockMacrosFromRunningInOfficeFilesFromTheInternet - choice definitions

const GpoItemChoice_t BlockMacrosFromRunningInOfficeFilesFromTheInternet_choice_Enabled = { L"Enabled", REG_DWORD, 1 };

// ------------------------------------------------------------------------------------------
// DisableAllUnsignedMacros - setting definitions

const GpoDefn_t DisableAllUnsignedMacros_1_vbawarnings = {
    false,
    szGpPath_MicrosoftAccess2016ApplicationSettingsSecurityTrustCenter,
    szGpName_VBAMacroNotificationSettings,
    szRegKey_softwarepoliciesmicrosoftoffice160accesssecurity,
    szRegVal_vbawarnings };
const GpoDefn_t DisableAllUnsignedMacros_2_vbarequirelmtrustedpublisher = {
    false,
    szGpPath_MicrosoftAccess2016ApplicationSettingsSecurityTrustCenter,
    szGpName_VBAMacroNotificationSettings__Blockcertificatesfromtrustedpublishersthatareonlyinstalledinthecurrentusercertificatestore,
    szRegKey_softwarepoliciesmicrosoftoffice160accesssecurity,
    szRegVal_vbarequirelmtrustedpublisher };
const GpoDefn_t DisableAllUnsignedMacros_3_vbarequiredigsigwithcodesigningeku = {
    false,
    szGpPath_MicrosoftAccess2016ApplicationSettingsSecurityTrustCenter,
    szGpName_VBAMacroNotificationSettings__RequireExtendedKeyUsageEKUforcertificatesfromtrustedpublishers,
    szRegKey_softwarepoliciesmicrosoftoffice160accesssecurity,
    szRegVal_vbarequiredigsigwithcodesigningeku };
const GpoDefn_t DisableAllUnsignedMacros_4_vbadigsigtrustedpublishers = {
    false,
    szGpPath_MicrosoftAccess2016ApplicationSettingsSecurityTrustCenter,
    szGpName_VBAMacroNotificationSettings__Requiremacrostobesignedbyatrustedpublisher,
    szRegKey_softwarepoliciesmicrosoftoffice160accesssecurity,
    szRegVal_vbadigsigtrustedpublishers };
const GpoDefn_t DisableAllUnsignedMacros_5_vbawarnings = {
    false,
    szGpPath_MicrosoftExcel2016ExcelOptionsSecurityTrustCenter,
    szGpName_MacroNotificationSettings,
    szRegKey_softwarepoliciesmicrosoftoffice160excelsecurity,
    szRegVal_vbawarnings };
const GpoDefn_t DisableAllUnsignedMacros_6_vbarequirelmtrustedpublisher = {
    false,
    szGpPath_MicrosoftExcel2016ExcelOptionsSecurityTrustCenter,
    szGpName_MacroNotificationSettings__Blockcertificatesfromtrustedpublishersthatareonlyinstalledinthecurrentusercertificatestore,
    szRegKey_softwarepoliciesmicrosoftoffice160excelsecurity,
    szRegVal_vbarequirelmtrustedpublisher };
const GpoDefn_t DisableAllUnsignedMacros_7_vbarequiredigsigwithcodesigningeku = {
    false,
    szGpPath_MicrosoftExcel2016ExcelOptionsSecurityTrustCenter,
    szGpName_MacroNotificationSettings__RequireExtendedKeyUsageEKUforcertificatesfromtrustedpublishers,
    szRegKey_softwarepoliciesmicrosoftoffice160excelsecurity,
    szRegVal_vbarequiredigsigwithcodesigningeku };
const GpoDefn_t DisableAllUnsignedMacros_8_vbadigsigtrustedpublishers = {
    false,
    szGpPath_MicrosoftExcel2016ExcelOptionsSecurityTrustCenter,
    szGpName_MacroNotificationSettings__Requiremacrostobesignedbyatrustedpublisher,
    szRegKey_softwarepoliciesmicrosoftoffice160excelsecurity,
    szRegVal_vbadigsigtrustedpublishers };
const GpoDefn_t DisableAllUnsignedMacros_9_vbawarnings = {
    false,
    szGpPath_MicrosoftPowerPoint2016PowerPointOptionsSecurityTrustCenter,
    szGpName_VBAMacroNotificationSettings,
    szRegKey_softwarepoliciesmicrosoftoffice160powerpointsecurity,
    szRegVal_vbawarnings };
const GpoDefn_t DisableAllUnsignedMacros_10_vbarequirelmtrustedpublisher = {
    false,
    szGpPath_MicrosoftPowerPoint2016PowerPointOptionsSecurityTrustCenter,
    szGpName_VBAMacroNotificationSettings__Blockcertificatesfromtrustedpublishersthatareonlyinstalledinthecurrentusercertificatestore,
    szRegKey_softwarepoliciesmicrosoftoffice160powerpointsecurity,
    szRegVal_vbarequirelmtrustedpublisher };
const GpoDefn_t DisableAllUnsignedMacros_11_vbarequiredigsigwithcodesigningeku = {
    false,
    szGpPath_MicrosoftPowerPoint2016PowerPointOptionsSecurityTrustCenter,
    szGpName_VBAMacroNotificationSettings__RequireExtendedKeyUsageEKUforcertificatesfromtrustedpublishers,
    szRegKey_softwarepoliciesmicrosoftoffice160powerpointsecurity,
    szRegVal_vbarequiredigsigwithcodesigningeku };
const GpoDefn_t DisableAllUnsignedMacros_12_vbadigsigtrustedpublishers = {
    false,
    szGpPath_MicrosoftPowerPoint2016PowerPointOptionsSecurityTrustCenter,
    szGpName_VBAMacroNotificationSettings__Requiremacrostobesignedbyatrustedpublisher,
    szRegKey_softwarepoliciesmicrosoftoffice160powerpointsecurity,
    szRegVal_vbadigsigtrustedpublishers };
const GpoDefn_t DisableAllUnsignedMacros_13_vbawarnings = {
    false,
    szGpPath_MicrosoftProject2016ProjectOptionsSecurityTrustCenter,
    szGpName_VBAMacroNotificationSettings,
    szRegKey_softwarepoliciesmicrosoftoffice160msprojectsecurity,
    szRegVal_vbawarnings };
const GpoDefn_t DisableAllUnsignedMacros_14_vbawarnings = {
    false,
    szGpPath_MicrosoftPublisher2016SecurityTrustCenter,
    szGpName_VBAMacroNotificationSettings,
    szRegKey_softwarepoliciesmicrosoftoffice160publishersecurity,
    szRegVal_vbawarnings };
const GpoDefn_t DisableAllUnsignedMacros_15_vbarequirelmtrustedpublisher = {
    false,
    szGpPath_MicrosoftPublisher2016SecurityTrustCenter,
    szGpName_VBAMacroNotificationSettings__Blockcertificatesfromtrustedpublishersthatareonlyinstalledinthecurrentusercertificatestore,
    szRegKey_softwarepoliciesmicrosoftoffice160publishersecurity,
    szRegVal_vbarequirelmtrustedpublisher };
const GpoDefn_t DisableAllUnsignedMacros_16_vbarequiredigsigwithcodesigningeku = {
    false,
    szGpPath_MicrosoftPublisher2016SecurityTrustCenter,
    szGpName_VBAMacroNotificationSettings__RequireExtendedKeyUsageEKUforcertificatesfromtrustedpublishers,
    szRegKey_softwarepoliciesmicrosoftoffice160publishersecurity,
    szRegVal_vbarequiredigsigwithcodesigningeku };
const GpoDefn_t DisableAllUnsignedMacros_17_vbadigsigtrustedpublishers = {
    false,
    szGpPath_MicrosoftPublisher2016SecurityTrustCenter,
    szGpName_VBAMacroNotificationSettings__Requiremacrostobesignedbyatrustedpublisher,
    szRegKey_softwarepoliciesmicrosoftoffice160publishersecurity,
    szRegVal_vbadigsigtrustedpublishers };
const GpoDefn_t DisableAllUnsignedMacros_18_vbawarnings = {
    false,
    szGpPath_MicrosoftVisio2016VisioOptionsSecurityTrustCenter,
    szGpName_VBAMacroNotificationSettings,
    szRegKey_softwarepoliciesmicrosoftoffice160visiosecurity,
    szRegVal_vbawarnings };
const GpoDefn_t DisableAllUnsignedMacros_19_vbarequirelmtrustedpublisher = {
    false,
    szGpPath_MicrosoftVisio2016VisioOptionsSecurityTrustCenter,
    szGpName_VBAMacroNotificationSettings__Blockcertificatesfromtrustedpublishersthatareonlyinstalledinthecurrentusercertificatestore,
    szRegKey_softwarepoliciesmicrosoftoffice160visiosecurity,
    szRegVal_vbarequirelmtrustedpublisher };
const GpoDefn_t DisableAllUnsignedMacros_20_vbarequiredigsigwithcodesigningeku = {
    false,
    szGpPath_MicrosoftVisio2016VisioOptionsSecurityTrustCenter,
    szGpName_VBAMacroNotificationSettings__RequireExtendedKeyUsageEKUforcertificatesfromtrustedpublishers,
    szRegKey_softwarepoliciesmicrosoftoffice160visiosecurity,
    szRegVal_vbarequiredigsigwithcodesigningeku };
const GpoDefn_t DisableAllUnsignedMacros_21_vbadigsigtrustedpublishers = {
    false,
    szGpPath_MicrosoftVisio2016VisioOptionsSecurityTrustCenter,
    szGpName_VBAMacroNotificationSettings__Requiremacrostobesignedbyatrustedpublisher,
    szRegKey_softwarepoliciesmicrosoftoffice160visiosecurity,
    szRegVal_vbadigsigtrustedpublishers };
const GpoDefn_t DisableAllUnsignedMacros_22_vbawarnings = {
    false,
    szGpPath_MicrosoftWord2016WordOptionsSecurityTrustCenter,
    szGpName_VBAMacroNotificationSettings,
    szRegKey_softwarepoliciesmicrosoftoffice160wordsecurity,
    szRegVal_vbawarnings };
const GpoDefn_t DisableAllUnsignedMacros_23_vbarequirelmtrustedpublisher = {
    false,
    szGpPath_MicrosoftWord2016WordOptionsSecurityTrustCenter,
    szGpName_VBAMacroNotificationSettings__Blockcertificatesfromtrustedpublishersthatareonlyinstalledinthecurrentusercertificatestore,
    szRegKey_softwarepoliciesmicrosoftoffice160wordsecurity,
    szRegVal_vbarequirelmtrustedpublisher };
const GpoDefn_t DisableAllUnsignedMacros_24_vbarequiredigsigwithcodesigningeku = {
    false,
    szGpPath_MicrosoftWord2016WordOptionsSecurityTrustCenter,
    szGpName_VBAMacroNotificationSettings__RequireExtendedKeyUsageEKUforcertificatesfromtrustedpublishers,
    szRegKey_softwarepoliciesmicrosoftoffice160wordsecurity,
    szRegVal_vbarequiredigsigwithcodesigningeku };
const GpoDefn_t DisableAllUnsignedMacros_25_vbadigsigtrustedpublishers = {
    false,
    szGpPath_MicrosoftWord2016WordOptionsSecurityTrustCenter,
    szGpName_VBAMacroNotificationSettings__Requiremacrostobesignedbyatrustedpublisher,
    szRegKey_softwarepoliciesmicrosoftoffice160wordsecurity,
    szRegVal_vbadigsigtrustedpublishers };

// DisableAllUnsignedMacros - choice definitions

const GpoItemChoice_t DisableAllUnsignedMacros_choice_Disableallexceptdigitallysignedmacros = { L"Disable all except digitally signed macros", REG_DWORD, 3 };
const GpoItemChoice_t DisableAllUnsignedMacros_choice_False = { L"False", REG_DWORD, 0 };
const GpoItemChoice_t DisableAllUnsignedMacros_choice_True = { L"True", REG_DWORD, 1 };
const GpoItemChoice_t DisableAllUnsignedMacros_choice_DisableVBAmacrosexceptdigitallysignedmacros = { L"Disable VBA macros except digitally signed macros", REG_DWORD, 3 };

// ------------------------------------------------------------------------------------------
// DisableAllTrustedLocations - setting definitions

const GpoDefn_t DisableAllTrustedLocations_1_alllocationsdisabled = {
    false,
    szGpPath_MicrosoftAccess2016ApplicationSettingsSecurityTrustCenterTrustedLocations,
    szGpName_Disablealltrustedlocations,
    szRegKey_softwarepoliciesmicrosoftoffice160accesssecuritytrustedlocations,
    szRegVal_alllocationsdisabled };
const GpoDefn_t DisableAllTrustedLocations_2_alllocationsdisabled = {
    false,
    szGpPath_MicrosoftExcel2016ExcelOptionsSecurityTrustCenterTrustedLocations,
    szGpName_Disablealltrustedlocations,
    szRegKey_softwarepoliciesmicrosoftoffice160excelsecuritytrustedlocations,
    szRegVal_alllocationsdisabled };
const GpoDefn_t DisableAllTrustedLocations_3_alllocationsdisabled = {
    false,
    szGpPath_MicrosoftPowerPoint2016PowerPointOptionsSecurityTrustCenterTrustedLocations,
    szGpName_Disablealltrustedlocations,
    szRegKey_softwarepoliciesmicrosoftoffice160powerpointsecuritytrustedlocations,
    szRegVal_alllocationsdisabled };
const GpoDefn_t DisableAllTrustedLocations_4_alllocationsdisabled = {
    false,
    szGpPath_MicrosoftProject2016ProjectOptionsSecurityTrustCenter,
    szGpName_Disablealltrustedlocations,
    szRegKey_softwarepoliciesmicrosoftoffice160msprojectsecuritytrustedlocations,
    szRegVal_alllocationsdisabled };
const GpoDefn_t DisableAllTrustedLocations_5_alllocationsdisabled = {
    false,
    szGpPath_MicrosoftVisio2016VisioOptionsSecurityTrustCenter,
    szGpName_Disablealltrustedlocations,
    szRegKey_softwarepoliciesmicrosoftoffice160visiosecuritytrustedlocations,
    szRegVal_alllocationsdisabled };
const GpoDefn_t DisableAllTrustedLocations_6_alllocationsdisabled = {
    false,
    szGpPath_MicrosoftWord2016WordOptionsSecurityTrustCenterTrustedLocations,
    szGpName_Disablealltrustedlocations,
    szRegKey_softwarepoliciesmicrosoftoffice160wordsecuritytrustedlocations,
    szRegVal_alllocationsdisabled };

// DisableAllTrustedLocations - choice definitions

const GpoItemChoice_t DisableAllTrustedLocations_choice_Enabled = { L"Enabled", REG_DWORD, 1 };

// ------------------------------------------------------------------------------------------
// ScanEncryptedMacros - setting definitions

const GpoDefn_t ScanEncryptedMacros_1_excelbypassencryptedmacroscan = {
    false,
    szGpPath_MicrosoftExcel2016ExcelOptionsSecurity,
    szGpName_ScanencryptedmacrosinExcelOpenXMLworkbooks,
    szRegKey_softwarepoliciesmicrosoftoffice160excelsecurity,
    szRegVal_excelbypassencryptedmacroscan };
const GpoDefn_t ScanEncryptedMacros_2_powerpointbypassencryptedmacroscan = {
    false,
    szGpPath_MicrosoftPowerPoint2016PowerPointOptionsSecurity,
    szGpName_ScanencryptedmacrosinPowerPointOpenXMLpresentations,
    szRegKey_softwarepoliciesmicrosoftoffice160powerpointsecurity,
    szRegVal_powerpointbypassencryptedmacroscan };
const GpoDefn_t ScanEncryptedMacros_3_wordbypassencryptedmacroscan = {
    false,
    szGpPath_MicrosoftWord2016WordOptionsSecurityTrustCenter,
    szGpName_ScanencryptedmacrosinWordOpenXMLdocuments,
    szRegKey_softwarepoliciesmicrosoftoffice160wordsecurity,
    szRegVal_wordbypassencryptedmacroscan };

// ScanEncryptedMacros - choice definitions

const GpoItemChoice_t ScanEncryptedMacros_choice_Scanencryptedmacrosdefault = { L"Scan encrypted macros (default)", REG_DWORD, 0 };

// ------------------------------------------------------------------------------------------
// DisableUnsignedVbaAddins - setting definitions

const GpoDefn_t DisableUnsignedVbaAddins_1_notbpromptunsignedaddin = {
    false,
    szGpPath_MicrosoftExcel2016ExcelOptionsSecurityTrustCenter,
    szGpName_DisableTrustBarNotificationforunsignedapplicationadd_insandblockthem,
    szRegKey_softwarepoliciesmicrosoftoffice160excelsecurity,
    szRegVal_notbpromptunsignedaddin };
const GpoDefn_t DisableUnsignedVbaAddins_2_requireaddinsig = {
    false,
    szGpPath_MicrosoftExcel2016ExcelOptionsSecurityTrustCenter,
    szGpName_Requirethatapplicationadd_insaresignedbyTrustedPublisher,
    szRegKey_softwarepoliciesmicrosoftoffice160excelsecurity,
    szRegVal_requireaddinsig };
const GpoDefn_t DisableUnsignedVbaAddins_3_notbpromptunsignedaddin = {
    false,
    szGpPath_MicrosoftPowerPoint2016PowerPointOptionsSecurityTrustCenter,
    szGpName_DisableTrustBarNotificationforunsignedapplicationadd_insandblockthem,
    szRegKey_softwarepoliciesmicrosoftoffice160powerpointsecurity,
    szRegVal_notbpromptunsignedaddin };
const GpoDefn_t DisableUnsignedVbaAddins_4_requireaddinsig = {
    false,
    szGpPath_MicrosoftPowerPoint2016PowerPointOptionsSecurityTrustCenter,
    szGpName_Requirethatapplicationadd_insaresignedbyTrustedPublisher,
    szRegKey_softwarepoliciesmicrosoftoffice160powerpointsecurity,
    szRegVal_requireaddinsig };

// DisableUnsignedVbaAddins - choice definitions

const GpoItemChoice_t DisableUnsignedVbaAddins_choice_Enabled = { L"Enabled", REG_DWORD, 1 };

// ------------------------------------------------------------------------------------------
// LegacyFileBlock - setting definitions

const GpoDefn_t LegacyFileBlock_1_dbasefiles = {
    false,
    szGpPath_MicrosoftExcel2016ExcelOptionsSecurityTrustCenterFileBlockSettings,
    szGpName_dBaseIIIIVfiles,
    szRegKey_softwarepoliciesmicrosoftoffice160excelsecurityfileblock,
    szRegVal_dbasefiles };
const GpoDefn_t LegacyFileBlock_2_difandsylkfiles = {
    false,
    szGpPath_MicrosoftExcel2016ExcelOptionsSecurityTrustCenterFileBlockSettings,
    szGpName_DifandSylkfiles,
    szRegKey_softwarepoliciesmicrosoftoffice160excelsecurityfileblock,
    szRegVal_difandsylkfiles };
const GpoDefn_t LegacyFileBlock_3_xl2macros = {
    false,
    szGpPath_MicrosoftExcel2016ExcelOptionsSecurityTrustCenterFileBlockSettings,
    szGpName_Excel2macrosheetsandadd_infiles,
    szRegKey_softwarepoliciesmicrosoftoffice160excelsecurityfileblock,
    szRegVal_xl2macros };
const GpoDefn_t LegacyFileBlock_4_xl2worksheets = {
    false,
    szGpPath_MicrosoftExcel2016ExcelOptionsSecurityTrustCenterFileBlockSettings,
    szGpName_Excel2worksheets,
    szRegKey_softwarepoliciesmicrosoftoffice160excelsecurityfileblock,
    szRegVal_xl2worksheets };
const GpoDefn_t LegacyFileBlock_5_xl3macros = {
    false,
    szGpPath_MicrosoftExcel2016ExcelOptionsSecurityTrustCenterFileBlockSettings,
    szGpName_Excel3macrosheetsandadd_infiles,
    szRegKey_softwarepoliciesmicrosoftoffice160excelsecurityfileblock,
    szRegVal_xl3macros };
const GpoDefn_t LegacyFileBlock_6_xl3worksheets = {
    false,
    szGpPath_MicrosoftExcel2016ExcelOptionsSecurityTrustCenterFileBlockSettings,
    szGpName_Excel3worksheets,
    szRegKey_softwarepoliciesmicrosoftoffice160excelsecurityfileblock,
    szRegVal_xl3worksheets };
const GpoDefn_t LegacyFileBlock_7_xl4macros = {
    false,
    szGpPath_MicrosoftExcel2016ExcelOptionsSecurityTrustCenterFileBlockSettings,
    szGpName_Excel4macrosheetsandadd_infiles,
    szRegKey_softwarepoliciesmicrosoftoffice160excelsecurityfileblock,
    szRegVal_xl4macros };
const GpoDefn_t LegacyFileBlock_8_xl4workbooks = {
    false,
    szGpPath_MicrosoftExcel2016ExcelOptionsSecurityTrustCenterFileBlockSettings,
    szGpName_Excel4workbooks,
    szRegKey_softwarepoliciesmicrosoftoffice160excelsecurityfileblock,
    szRegVal_xl4workbooks };
const GpoDefn_t LegacyFileBlock_9_xl4worksheets = {
    false,
    szGpPath_MicrosoftExcel2016ExcelOptionsSecurityTrustCenterFileBlockSettings,
    szGpName_Excel4worksheets,
    szRegKey_softwarepoliciesmicrosoftoffice160excelsecurityfileblock,
    szRegVal_xl4worksheets };
const GpoDefn_t LegacyFileBlock_10_xl95workbooks = {
    false,
    szGpPath_MicrosoftExcel2016ExcelOptionsSecurityTrustCenterFileBlockSettings,
    szGpName_Excel95workbooks,
    szRegKey_softwarepoliciesmicrosoftoffice160excelsecurityfileblock,
    szRegVal_xl95workbooks };
const GpoDefn_t LegacyFileBlock_11_xl9597workbooksandtemplates = {
    false,
    szGpPath_MicrosoftExcel2016ExcelOptionsSecurityTrustCenterFileBlockSettings,
    szGpName_Excel95_97workbooksandtemplates,
    szRegKey_softwarepoliciesmicrosoftoffice160excelsecurityfileblock,
    szRegVal_xl9597workbooksandtemplates };
const GpoDefn_t LegacyFileBlock_12_xl97workbooksandtemplates = {
    false,
    szGpPath_MicrosoftExcel2016ExcelOptionsSecurityTrustCenterFileBlockSettings,
    szGpName_Excel97_2003workbooksandtemplates,
    szRegKey_softwarepoliciesmicrosoftoffice160excelsecurityfileblock,
    szRegVal_xl97workbooksandtemplates };
const GpoDefn_t LegacyFileBlock_13_openinprotectedview = {
    false,
    szGpPath_MicrosoftExcel2016ExcelOptionsSecurityTrustCenterFileBlockSettings,
    szGpName_Setdefaultfileblockbehavior,
    szRegKey_softwarepoliciesmicrosoftoffice160excelsecurityfileblock,
    szRegVal_openinprotectedview };
const GpoDefn_t LegacyFileBlock_14_htmlandxmlssfiles = {
    false,
    szGpPath_MicrosoftExcel2016ExcelOptionsSecurityTrustCenterFileBlockSettings,
    szGpName_WebpagesandExcel2003XMLspreadsheets,
    szRegKey_softwarepoliciesmicrosoftoffice160excelsecurityfileblock,
    szRegVal_htmlandxmlssfiles };
const GpoDefn_t LegacyFileBlock_15_binaryfiles = {
    false,
    szGpPath_MicrosoftPowerPoint2016PowerPointOptionsSecurityTrustCenterFileBlockSettings,
    szGpName_PowerPoint97_2003presentationsshowstemplatesandadd_infiles,
    szRegKey_softwarepoliciesmicrosoftoffice160powerpointsecurityfileblock,
    szRegVal_binaryfiles };
const GpoDefn_t LegacyFileBlock_16_openinprotectedview = {
    false,
    szGpPath_MicrosoftPowerPoint2016PowerPointOptionsSecurityTrustCenterFileBlockSettings,
    szGpName_Setdefaultfileblockbehavior,
    szRegKey_softwarepoliciesmicrosoftoffice160powerpointsecurityfileblock,
    szRegVal_openinprotectedview };
const GpoDefn_t LegacyFileBlock_17_legacyfiles = {
    false,
    szGpPath_MicrosoftProject2016ProjectOptionsSecurity,
    szGpName_Previous_versionfileformats,
    szRegKey_softwarepoliciesmicrosoftoffice160msprojectsecurity,
    szRegVal_legacyfiles };
const GpoDefn_t LegacyFileBlock_18_visio2000files = {
    false,
    szGpPath_MicrosoftVisio2016VisioOptionsSecurityTrustCenterFileBlockSettings,
    szGpName_Visio2000_2002BinaryDrawingsTemplatesandStencils,
    szRegKey_softwarepoliciesmicrosoftoffice160visiosecurityfileblock,
    szRegVal_visio2000files };
const GpoDefn_t LegacyFileBlock_19_visio2003files = {
    false,
    szGpPath_MicrosoftVisio2016VisioOptionsSecurityTrustCenterFileBlockSettings,
    szGpName_Visio2003_2010BinaryDrawingsTemplatesandStencils,
    szRegKey_softwarepoliciesmicrosoftoffice160visiosecurityfileblock,
    szRegVal_visio2003files };
const GpoDefn_t LegacyFileBlock_20_visio50andearlierfiles = {
    false,
    szGpPath_MicrosoftVisio2016VisioOptionsSecurityTrustCenterFileBlockSettings,
    szGpName_Visio50orearlierBinaryDrawingsTemplatesandStencils,
    szRegKey_softwarepoliciesmicrosoftoffice160visiosecurityfileblock,
    szRegVal_visio50andearlierfiles };
const GpoDefn_t LegacyFileBlock_21_openinprotectedview = {
    false,
    szGpPath_MicrosoftWord2016WordOptionsSecurityTrustCenterFileBlockSettings,
    szGpName_Setdefaultfileblockbehavior,
    szRegKey_softwarepoliciesmicrosoftoffice160wordsecurityfileblock,
    szRegVal_openinprotectedview };
const GpoDefn_t LegacyFileBlock_22_word2files = {
    false,
    szGpPath_MicrosoftWord2016WordOptionsSecurityTrustCenterFileBlockSettings,
    szGpName_Word2andearlierbinarydocumentsandtemplates,
    szRegKey_softwarepoliciesmicrosoftoffice160wordsecurityfileblock,
    szRegVal_word2files };
const GpoDefn_t LegacyFileBlock_23_word2000files = {
    false,
    szGpPath_MicrosoftWord2016WordOptionsSecurityTrustCenterFileBlockSettings,
    szGpName_Word2000binarydocumentsandtemplates,
    szRegKey_softwarepoliciesmicrosoftoffice160wordsecurityfileblock,
    szRegVal_word2000files };
const GpoDefn_t LegacyFileBlock_24_word2003files = {
    false,
    szGpPath_MicrosoftWord2016WordOptionsSecurityTrustCenterFileBlockSettings,
    szGpName_Word2003binarydocumentsandtemplates,
    szRegKey_softwarepoliciesmicrosoftoffice160wordsecurityfileblock,
    szRegVal_word2003files };
const GpoDefn_t LegacyFileBlock_25_word2007files = {
    false,
    szGpPath_MicrosoftWord2016WordOptionsSecurityTrustCenterFileBlockSettings,
    szGpName_Word2007andlaterbinarydocumentsandtemplates,
    szRegKey_softwarepoliciesmicrosoftoffice160wordsecurityfileblock,
    szRegVal_word2007files };
const GpoDefn_t LegacyFileBlock_26_word60files = {
    false,
    szGpPath_MicrosoftWord2016WordOptionsSecurityTrustCenterFileBlockSettings,
    szGpName_Word60binarydocumentsandtemplates,
    szRegKey_softwarepoliciesmicrosoftoffice160wordsecurityfileblock,
    szRegVal_word60files };
const GpoDefn_t LegacyFileBlock_27_word95files = {
    false,
    szGpPath_MicrosoftWord2016WordOptionsSecurityTrustCenterFileBlockSettings,
    szGpName_Word95binarydocumentsandtemplates,
    szRegKey_softwarepoliciesmicrosoftoffice160wordsecurityfileblock,
    szRegVal_word95files };
const GpoDefn_t LegacyFileBlock_28_word97files = {
    false,
    szGpPath_MicrosoftWord2016WordOptionsSecurityTrustCenterFileBlockSettings,
    szGpName_Word97binarydocumentsandtemplates,
    szRegKey_softwarepoliciesmicrosoftoffice160wordsecurityfileblock,
    szRegVal_word97files };
const GpoDefn_t LegacyFileBlock_29_wordxpfiles = {
    false,
    szGpPath_MicrosoftWord2016WordOptionsSecurityTrustCenterFileBlockSettings,
    szGpName_WordXPbinarydocumentsandtemplates,
    szRegKey_softwarepoliciesmicrosoftoffice160wordsecurityfileblock,
    szRegVal_wordxpfiles };

// LegacyFileBlock - choice definitions

const GpoItemChoice_t LegacyFileBlock_choice_OpenSaveblockeduseopenpolicy = { L"Open/Save blocked, use open policy", REG_DWORD, 2 };
const GpoItemChoice_t LegacyFileBlock_choice_Blockedfilesarenotopened = { L"Blocked files are not opened", REG_DWORD, 0 };
const GpoItemChoice_t LegacyFileBlock_choice_Donotopenorsave = { L"Do not open or save", REG_DWORD, 0 };
const GpoItemChoice_t LegacyFileBlock_choice_OpenSaveblocked = { L"Open/Save blocked", REG_DWORD, 2 };

// ------------------------------------------------------------------------------------------

// Null defs to end arrays
const GpoDefn_t NULL_GpoDefn = {
    false,
    NULL,
    NULL,
    NULL,
    NULL };

const GpoItemChoice_t NULL_GpoItemChoice = { NULL, REG_NONE, 0 };

// ------------------------------------------------------------------------------------------
// DisableAllVBA

const GpoItem_t DisableAllVBA[] = {
    { DisableAllVBA_1_vbaoff, DisableAllVBA_choice_Enabled },
    { NULL_GpoDefn, NULL_GpoItemChoice } };

// ASR-Audit

const GpoItem_t ASR_Audit[] = {
    { ASR_1_ExploitGuard_ASR_Rules, ASR_choice_Enabled },
    { ASR_2_26190899_1602_49e8_8b27_eb1d0a1ce869, ASR_choice_Audit },
    { ASR_3_3b576869_a4ec_4529_8536_b80a7769e899, ASR_choice_Audit },
    { ASR_4_75668c1f_73b5_4cf0_bb93_3ecf5cb7cc84, ASR_choice_Audit },
    { ASR_5_92E97FA1_2EDF_4476_BDD6_9DD0B4DDDC7B, ASR_choice_Audit },
    { ASR_6_d4f940ab_401b_4efc_aadc_ad5f3c50688a, ASR_choice_Audit },
    { ASR_7_DisableRealtimeMonitoring, ASR_choice_Disabled },
    { NULL_GpoDefn, NULL_GpoItemChoice } };

// ASR-Block

const GpoItem_t ASR_Block[] = {
    { ASR_1_ExploitGuard_ASR_Rules, ASR_choice_Enabled },
    { ASR_2_26190899_1602_49e8_8b27_eb1d0a1ce869, ASR_choice_Block },
    { ASR_3_3b576869_a4ec_4529_8536_b80a7769e899, ASR_choice_Block },
    { ASR_4_75668c1f_73b5_4cf0_bb93_3ecf5cb7cc84, ASR_choice_Block },
    { ASR_5_92E97FA1_2EDF_4476_BDD6_9DD0B4DDDC7B, ASR_choice_Block },
    { ASR_6_d4f940ab_401b_4efc_aadc_ad5f3c50688a, ASR_choice_Block },
    { ASR_7_DisableRealtimeMonitoring, ASR_choice_Disabled },
    { NULL_GpoDefn, NULL_GpoItemChoice } };

// ASR-Off

const GpoItem_t ASR_Off[] = {
    { ASR_1_ExploitGuard_ASR_Rules, ASR_choice_Enabled },
    { ASR_2_26190899_1602_49e8_8b27_eb1d0a1ce869, ASR_choice_Off },
    { ASR_3_3b576869_a4ec_4529_8536_b80a7769e899, ASR_choice_Off },
    { ASR_4_75668c1f_73b5_4cf0_bb93_3ecf5cb7cc84, ASR_choice_Off },
    { ASR_5_92E97FA1_2EDF_4476_BDD6_9DD0B4DDDC7B, ASR_choice_Off },
    { ASR_6_d4f940ab_401b_4efc_aadc_ad5f3c50688a, ASR_choice_Off },
    { ASR_7_DisableRealtimeMonitoring, ASR_choice_Disabled },
    { NULL_GpoDefn, NULL_GpoItemChoice } };

// ASR-Warn

const GpoItem_t ASR_Warn[] = {
    { ASR_1_ExploitGuard_ASR_Rules, ASR_choice_Enabled },
    { ASR_2_26190899_1602_49e8_8b27_eb1d0a1ce869, ASR_choice_Warn },
    { ASR_3_3b576869_a4ec_4529_8536_b80a7769e899, ASR_choice_Warn },
    { ASR_4_75668c1f_73b5_4cf0_bb93_3ecf5cb7cc84, ASR_choice_Warn },
    { ASR_5_92E97FA1_2EDF_4476_BDD6_9DD0B4DDDC7B, ASR_choice_Warn },
    { ASR_6_d4f940ab_401b_4efc_aadc_ad5f3c50688a, ASR_choice_Warn },
    { ASR_7_DisableRealtimeMonitoring, ASR_choice_Disabled },
    { NULL_GpoDefn, NULL_GpoItemChoice } };

// BlockMacrosFromRunningInOfficeFilesFromTheInternet

const GpoItem_t BlockMacrosFromRunningInOfficeFilesFromTheInternet[] = {
    { BlockMacrosFromRunningInOfficeFilesFromTheInternet_1_blockcontentexecutionfrominternet, BlockMacrosFromRunningInOfficeFilesFromTheInternet_choice_Enabled },
    { BlockMacrosFromRunningInOfficeFilesFromTheInternet_2_blockcontentexecutionfrominternet, BlockMacrosFromRunningInOfficeFilesFromTheInternet_choice_Enabled },
    { BlockMacrosFromRunningInOfficeFilesFromTheInternet_3_blockcontentexecutionfrominternet, BlockMacrosFromRunningInOfficeFilesFromTheInternet_choice_Enabled },
    { BlockMacrosFromRunningInOfficeFilesFromTheInternet_4_blockcontentexecutionfrominternet, BlockMacrosFromRunningInOfficeFilesFromTheInternet_choice_Enabled },
    { BlockMacrosFromRunningInOfficeFilesFromTheInternet_5_blockcontentexecutionfrominternet, BlockMacrosFromRunningInOfficeFilesFromTheInternet_choice_Enabled },
    { NULL_GpoDefn, NULL_GpoItemChoice } };

// DisableAllUnsignedMacros-basic

const GpoItem_t DisableAllUnsignedMacros_basic[] = {
    { DisableAllUnsignedMacros_1_vbawarnings, DisableAllUnsignedMacros_choice_Disableallexceptdigitallysignedmacros },
    { DisableAllUnsignedMacros_2_vbarequirelmtrustedpublisher, DisableAllUnsignedMacros_choice_False },
    { DisableAllUnsignedMacros_3_vbarequiredigsigwithcodesigningeku, DisableAllUnsignedMacros_choice_False },
    { DisableAllUnsignedMacros_4_vbadigsigtrustedpublishers, DisableAllUnsignedMacros_choice_False },
    { DisableAllUnsignedMacros_5_vbawarnings, DisableAllUnsignedMacros_choice_DisableVBAmacrosexceptdigitallysignedmacros },
    { DisableAllUnsignedMacros_6_vbarequirelmtrustedpublisher, DisableAllUnsignedMacros_choice_False },
    { DisableAllUnsignedMacros_7_vbarequiredigsigwithcodesigningeku, DisableAllUnsignedMacros_choice_False },
    { DisableAllUnsignedMacros_8_vbadigsigtrustedpublishers, DisableAllUnsignedMacros_choice_False },
    { DisableAllUnsignedMacros_9_vbawarnings, DisableAllUnsignedMacros_choice_Disableallexceptdigitallysignedmacros },
    { DisableAllUnsignedMacros_10_vbarequirelmtrustedpublisher, DisableAllUnsignedMacros_choice_False },
    { DisableAllUnsignedMacros_11_vbarequiredigsigwithcodesigningeku, DisableAllUnsignedMacros_choice_False },
    { DisableAllUnsignedMacros_12_vbadigsigtrustedpublishers, DisableAllUnsignedMacros_choice_False },
    { DisableAllUnsignedMacros_13_vbawarnings, DisableAllUnsignedMacros_choice_Disableallexceptdigitallysignedmacros },
    { DisableAllUnsignedMacros_14_vbawarnings, DisableAllUnsignedMacros_choice_Disableallexceptdigitallysignedmacros },
    { DisableAllUnsignedMacros_15_vbarequirelmtrustedpublisher, DisableAllUnsignedMacros_choice_False },
    { DisableAllUnsignedMacros_16_vbarequiredigsigwithcodesigningeku, DisableAllUnsignedMacros_choice_False },
    { DisableAllUnsignedMacros_17_vbadigsigtrustedpublishers, DisableAllUnsignedMacros_choice_False },
    { DisableAllUnsignedMacros_18_vbawarnings, DisableAllUnsignedMacros_choice_Disableallexceptdigitallysignedmacros },
    { DisableAllUnsignedMacros_19_vbarequirelmtrustedpublisher, DisableAllUnsignedMacros_choice_False },
    { DisableAllUnsignedMacros_20_vbarequiredigsigwithcodesigningeku, DisableAllUnsignedMacros_choice_False },
    { DisableAllUnsignedMacros_21_vbadigsigtrustedpublishers, DisableAllUnsignedMacros_choice_False },
    { DisableAllUnsignedMacros_22_vbawarnings, DisableAllUnsignedMacros_choice_Disableallexceptdigitallysignedmacros },
    { DisableAllUnsignedMacros_23_vbarequirelmtrustedpublisher, DisableAllUnsignedMacros_choice_False },
    { DisableAllUnsignedMacros_24_vbarequiredigsigwithcodesigningeku, DisableAllUnsignedMacros_choice_False },
    { DisableAllUnsignedMacros_25_vbadigsigtrustedpublishers, DisableAllUnsignedMacros_choice_False },
    { NULL_GpoDefn, NULL_GpoItemChoice } };

// DisableAllUnsignedMacros-reqTrustedPub

const GpoItem_t DisableAllUnsignedMacros_reqTrustedPub[] = {
    { DisableAllUnsignedMacros_1_vbawarnings, DisableAllUnsignedMacros_choice_Disableallexceptdigitallysignedmacros },
    { DisableAllUnsignedMacros_2_vbarequirelmtrustedpublisher, DisableAllUnsignedMacros_choice_False },
    { DisableAllUnsignedMacros_3_vbarequiredigsigwithcodesigningeku, DisableAllUnsignedMacros_choice_False },
    { DisableAllUnsignedMacros_4_vbadigsigtrustedpublishers, DisableAllUnsignedMacros_choice_True },
    { DisableAllUnsignedMacros_5_vbawarnings, DisableAllUnsignedMacros_choice_DisableVBAmacrosexceptdigitallysignedmacros },
    { DisableAllUnsignedMacros_6_vbarequirelmtrustedpublisher, DisableAllUnsignedMacros_choice_False },
    { DisableAllUnsignedMacros_7_vbarequiredigsigwithcodesigningeku, DisableAllUnsignedMacros_choice_False },
    { DisableAllUnsignedMacros_8_vbadigsigtrustedpublishers, DisableAllUnsignedMacros_choice_True },
    { DisableAllUnsignedMacros_9_vbawarnings, DisableAllUnsignedMacros_choice_Disableallexceptdigitallysignedmacros },
    { DisableAllUnsignedMacros_10_vbarequirelmtrustedpublisher, DisableAllUnsignedMacros_choice_False },
    { DisableAllUnsignedMacros_11_vbarequiredigsigwithcodesigningeku, DisableAllUnsignedMacros_choice_False },
    { DisableAllUnsignedMacros_12_vbadigsigtrustedpublishers, DisableAllUnsignedMacros_choice_True },
    { DisableAllUnsignedMacros_13_vbawarnings, DisableAllUnsignedMacros_choice_Disableallexceptdigitallysignedmacros },
    { DisableAllUnsignedMacros_14_vbawarnings, DisableAllUnsignedMacros_choice_Disableallexceptdigitallysignedmacros },
    { DisableAllUnsignedMacros_15_vbarequirelmtrustedpublisher, DisableAllUnsignedMacros_choice_False },
    { DisableAllUnsignedMacros_16_vbarequiredigsigwithcodesigningeku, DisableAllUnsignedMacros_choice_False },
    { DisableAllUnsignedMacros_17_vbadigsigtrustedpublishers, DisableAllUnsignedMacros_choice_True },
    { DisableAllUnsignedMacros_18_vbawarnings, DisableAllUnsignedMacros_choice_Disableallexceptdigitallysignedmacros },
    { DisableAllUnsignedMacros_19_vbarequirelmtrustedpublisher, DisableAllUnsignedMacros_choice_False },
    { DisableAllUnsignedMacros_20_vbarequiredigsigwithcodesigningeku, DisableAllUnsignedMacros_choice_False },
    { DisableAllUnsignedMacros_21_vbadigsigtrustedpublishers, DisableAllUnsignedMacros_choice_True },
    { DisableAllUnsignedMacros_22_vbawarnings, DisableAllUnsignedMacros_choice_Disableallexceptdigitallysignedmacros },
    { DisableAllUnsignedMacros_23_vbarequirelmtrustedpublisher, DisableAllUnsignedMacros_choice_False },
    { DisableAllUnsignedMacros_24_vbarequiredigsigwithcodesigningeku, DisableAllUnsignedMacros_choice_False },
    { DisableAllUnsignedMacros_25_vbadigsigtrustedpublishers, DisableAllUnsignedMacros_choice_True },
    { NULL_GpoDefn, NULL_GpoItemChoice } };

// DisableAllUnsignedMacros-strict

const GpoItem_t DisableAllUnsignedMacros_strict[] = {
    { DisableAllUnsignedMacros_1_vbawarnings, DisableAllUnsignedMacros_choice_Disableallexceptdigitallysignedmacros },
    { DisableAllUnsignedMacros_2_vbarequirelmtrustedpublisher, DisableAllUnsignedMacros_choice_True },
    { DisableAllUnsignedMacros_3_vbarequiredigsigwithcodesigningeku, DisableAllUnsignedMacros_choice_True },
    { DisableAllUnsignedMacros_4_vbadigsigtrustedpublishers, DisableAllUnsignedMacros_choice_True },
    { DisableAllUnsignedMacros_5_vbawarnings, DisableAllUnsignedMacros_choice_DisableVBAmacrosexceptdigitallysignedmacros },
    { DisableAllUnsignedMacros_6_vbarequirelmtrustedpublisher, DisableAllUnsignedMacros_choice_True },
    { DisableAllUnsignedMacros_7_vbarequiredigsigwithcodesigningeku, DisableAllUnsignedMacros_choice_True },
    { DisableAllUnsignedMacros_8_vbadigsigtrustedpublishers, DisableAllUnsignedMacros_choice_True },
    { DisableAllUnsignedMacros_9_vbawarnings, DisableAllUnsignedMacros_choice_Disableallexceptdigitallysignedmacros },
    { DisableAllUnsignedMacros_10_vbarequirelmtrustedpublisher, DisableAllUnsignedMacros_choice_True },
    { DisableAllUnsignedMacros_11_vbarequiredigsigwithcodesigningeku, DisableAllUnsignedMacros_choice_True },
    { DisableAllUnsignedMacros_12_vbadigsigtrustedpublishers, DisableAllUnsignedMacros_choice_True },
    { DisableAllUnsignedMacros_13_vbawarnings, DisableAllUnsignedMacros_choice_Disableallexceptdigitallysignedmacros },
    { DisableAllUnsignedMacros_14_vbawarnings, DisableAllUnsignedMacros_choice_Disableallexceptdigitallysignedmacros },
    { DisableAllUnsignedMacros_15_vbarequirelmtrustedpublisher, DisableAllUnsignedMacros_choice_True },
    { DisableAllUnsignedMacros_16_vbarequiredigsigwithcodesigningeku, DisableAllUnsignedMacros_choice_True },
    { DisableAllUnsignedMacros_17_vbadigsigtrustedpublishers, DisableAllUnsignedMacros_choice_True },
    { DisableAllUnsignedMacros_18_vbawarnings, DisableAllUnsignedMacros_choice_Disableallexceptdigitallysignedmacros },
    { DisableAllUnsignedMacros_19_vbarequirelmtrustedpublisher, DisableAllUnsignedMacros_choice_True },
    { DisableAllUnsignedMacros_20_vbarequiredigsigwithcodesigningeku, DisableAllUnsignedMacros_choice_True },
    { DisableAllUnsignedMacros_21_vbadigsigtrustedpublishers, DisableAllUnsignedMacros_choice_True },
    { DisableAllUnsignedMacros_22_vbawarnings, DisableAllUnsignedMacros_choice_Disableallexceptdigitallysignedmacros },
    { DisableAllUnsignedMacros_23_vbarequirelmtrustedpublisher, DisableAllUnsignedMacros_choice_True },
    { DisableAllUnsignedMacros_24_vbarequiredigsigwithcodesigningeku, DisableAllUnsignedMacros_choice_True },
    { DisableAllUnsignedMacros_25_vbadigsigtrustedpublishers, DisableAllUnsignedMacros_choice_True },
    { NULL_GpoDefn, NULL_GpoItemChoice } };

// DisableAllTrustedLocations

const GpoItem_t DisableAllTrustedLocations[] = {
    { DisableAllTrustedLocations_1_alllocationsdisabled, DisableAllTrustedLocations_choice_Enabled },
    { DisableAllTrustedLocations_2_alllocationsdisabled, DisableAllTrustedLocations_choice_Enabled },
    { DisableAllTrustedLocations_3_alllocationsdisabled, DisableAllTrustedLocations_choice_Enabled },
    { DisableAllTrustedLocations_4_alllocationsdisabled, DisableAllTrustedLocations_choice_Enabled },
    { DisableAllTrustedLocations_5_alllocationsdisabled, DisableAllTrustedLocations_choice_Enabled },
    { DisableAllTrustedLocations_6_alllocationsdisabled, DisableAllTrustedLocations_choice_Enabled },
    { NULL_GpoDefn, NULL_GpoItemChoice } };

// ScanEncryptedMacros

const GpoItem_t ScanEncryptedMacros[] = {
    { ScanEncryptedMacros_1_excelbypassencryptedmacroscan, ScanEncryptedMacros_choice_Scanencryptedmacrosdefault },
    { ScanEncryptedMacros_2_powerpointbypassencryptedmacroscan, ScanEncryptedMacros_choice_Scanencryptedmacrosdefault },
    { ScanEncryptedMacros_3_wordbypassencryptedmacroscan, ScanEncryptedMacros_choice_Scanencryptedmacrosdefault },
    { NULL_GpoDefn, NULL_GpoItemChoice } };

// DisableUnsignedVbaAddins

const GpoItem_t DisableUnsignedVbaAddins[] = {
    { DisableUnsignedVbaAddins_1_notbpromptunsignedaddin, DisableUnsignedVbaAddins_choice_Enabled },
    { DisableUnsignedVbaAddins_2_requireaddinsig, DisableUnsignedVbaAddins_choice_Enabled },
    { DisableUnsignedVbaAddins_3_notbpromptunsignedaddin, DisableUnsignedVbaAddins_choice_Enabled },
    { DisableUnsignedVbaAddins_4_requireaddinsig, DisableUnsignedVbaAddins_choice_Enabled },
    { NULL_GpoDefn, NULL_GpoItemChoice } };

// LegacyFileBlock

const GpoItem_t LegacyFileBlock[] = {
    { LegacyFileBlock_1_dbasefiles, LegacyFileBlock_choice_OpenSaveblockeduseopenpolicy },
    { LegacyFileBlock_2_difandsylkfiles, LegacyFileBlock_choice_OpenSaveblockeduseopenpolicy },
    { LegacyFileBlock_3_xl2macros, LegacyFileBlock_choice_OpenSaveblockeduseopenpolicy },
    { LegacyFileBlock_4_xl2worksheets, LegacyFileBlock_choice_OpenSaveblockeduseopenpolicy },
    { LegacyFileBlock_5_xl3macros, LegacyFileBlock_choice_OpenSaveblockeduseopenpolicy },
    { LegacyFileBlock_6_xl3worksheets, LegacyFileBlock_choice_OpenSaveblockeduseopenpolicy },
    { LegacyFileBlock_7_xl4macros, LegacyFileBlock_choice_OpenSaveblockeduseopenpolicy },
    { LegacyFileBlock_8_xl4workbooks, LegacyFileBlock_choice_OpenSaveblockeduseopenpolicy },
    { LegacyFileBlock_9_xl4worksheets, LegacyFileBlock_choice_OpenSaveblockeduseopenpolicy },
    { LegacyFileBlock_10_xl95workbooks, LegacyFileBlock_choice_OpenSaveblockeduseopenpolicy },
    { LegacyFileBlock_11_xl9597workbooksandtemplates, LegacyFileBlock_choice_OpenSaveblockeduseopenpolicy },
    { LegacyFileBlock_12_xl97workbooksandtemplates, LegacyFileBlock_choice_OpenSaveblockeduseopenpolicy },
    { LegacyFileBlock_13_openinprotectedview, LegacyFileBlock_choice_Blockedfilesarenotopened },
    { LegacyFileBlock_14_htmlandxmlssfiles, LegacyFileBlock_choice_OpenSaveblockeduseopenpolicy },
    { LegacyFileBlock_15_binaryfiles, LegacyFileBlock_choice_OpenSaveblockeduseopenpolicy },
    { LegacyFileBlock_16_openinprotectedview, LegacyFileBlock_choice_Blockedfilesarenotopened },
    { LegacyFileBlock_17_legacyfiles, LegacyFileBlock_choice_Donotopenorsave },
    { LegacyFileBlock_18_visio2000files, LegacyFileBlock_choice_OpenSaveblocked },
    { LegacyFileBlock_19_visio2003files, LegacyFileBlock_choice_OpenSaveblocked },
    { LegacyFileBlock_20_visio50andearlierfiles, LegacyFileBlock_choice_OpenSaveblocked },
    { LegacyFileBlock_21_openinprotectedview, LegacyFileBlock_choice_Blockedfilesarenotopened },
    { LegacyFileBlock_22_word2files, LegacyFileBlock_choice_OpenSaveblockeduseopenpolicy },
    { LegacyFileBlock_23_word2000files, LegacyFileBlock_choice_OpenSaveblockeduseopenpolicy },
    { LegacyFileBlock_24_word2003files, LegacyFileBlock_choice_OpenSaveblockeduseopenpolicy },
    { LegacyFileBlock_25_word2007files, LegacyFileBlock_choice_OpenSaveblockeduseopenpolicy },
    { LegacyFileBlock_26_word60files, LegacyFileBlock_choice_OpenSaveblockeduseopenpolicy },
    { LegacyFileBlock_27_word95files, LegacyFileBlock_choice_OpenSaveblockeduseopenpolicy },
    { LegacyFileBlock_28_word97files, LegacyFileBlock_choice_OpenSaveblockeduseopenpolicy },
    { LegacyFileBlock_29_wordxpfiles, LegacyFileBlock_choice_OpenSaveblockeduseopenpolicy },
    { NULL_GpoDefn, NULL_GpoItemChoice } };


// ------------------------------------------------------------------------------------------
