// OfficeMacroKeysToClean.h
// GPO keys to clean if empty, in order

#include "OfficeMacroKeysToClean.h"

// All the below is autogenerated using GpoKeysToCleanUp.ps1.

// Machine paths:
const wchar_t* MachineKeysToCleanUp[] = {
    L"Software\\Policies\\Microsoft\\Windows Defender\\Windows Defender Exploit Guard\\ASR\\Rules",
    L"Software\\Policies\\Microsoft\\Windows Defender\\Windows Defender Exploit Guard\\ASR",
    L"Software\\Policies\\Microsoft\\Windows Defender\\Windows Defender Exploit Guard",
    L"Software\\Policies\\Microsoft\\Windows Defender\\Real-Time Protection",
    L"Software\\Policies\\Microsoft\\Windows Defender",
    L"Software\\Policies\\Microsoft\\Windows",
    L"Software\\Policies\\Microsoft",
    L"Software\\Policies",
    L"Software",
    nullptr
};

// User paths:
const wchar_t* UserKeysToCleanUp[] = {
    L"software\\policies\\microsoft\\office\\16.0\\word\\security\\trusted locations",
    L"software\\policies\\microsoft\\office\\16.0\\word\\security\\fileblock",
    L"software\\policies\\microsoft\\office\\16.0\\word\\security",
    L"software\\policies\\microsoft\\office\\16.0\\word",
    L"software\\policies\\microsoft\\office\\16.0\\visio\\security\\trusted locations",
    L"software\\policies\\microsoft\\office\\16.0\\visio\\security\\fileblock",
    L"software\\policies\\microsoft\\office\\16.0\\visio\\security",
    L"software\\policies\\microsoft\\office\\16.0\\visio",
    L"software\\policies\\microsoft\\office\\16.0\\publisher\\security",
    L"software\\policies\\microsoft\\office\\16.0\\publisher",
    L"software\\policies\\microsoft\\office\\16.0\\powerpoint\\security\\trusted locations",
    L"software\\policies\\microsoft\\office\\16.0\\powerpoint\\security\\fileblock",
    L"software\\policies\\microsoft\\office\\16.0\\powerpoint\\security",
    L"software\\policies\\microsoft\\office\\16.0\\powerpoint",
    L"software\\policies\\microsoft\\office\\16.0\\ms project\\security\\trusted locations",
    L"software\\policies\\microsoft\\office\\16.0\\ms project\\security",
    L"software\\policies\\microsoft\\office\\16.0\\ms project",
    L"software\\policies\\microsoft\\office\\16.0\\excel\\security\\trusted locations",
    L"software\\policies\\microsoft\\office\\16.0\\excel\\security\\fileblock",
    L"software\\policies\\microsoft\\office\\16.0\\excel\\security",
    L"software\\policies\\microsoft\\office\\16.0\\excel",
    L"software\\policies\\microsoft\\office\\16.0\\access\\security\\trusted locations",
    L"software\\policies\\microsoft\\office\\16.0\\access\\security",
    L"software\\policies\\microsoft\\office\\16.0\\access",
    L"software\\policies\\microsoft\\office\\16.0",
    L"software\\policies\\microsoft\\office",
    L"software\\policies\\microsoft",
    L"software\\policies",
    L"software",
    nullptr
};



